# Generated by Django 5.2.8 on 2025-11-15 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_categoria_livros_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2025, 11, 15)),
        ),
    ]
