# Generated by Django 5.2.8 on 2025-11-15 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_livros_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='tempo_duracao',
        ),
    ]
