# Generated by Django 5.2.8 on 2025-11-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_remove_livros_tempo_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='nome_emprestado',
        ),
        migrations.AddField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
    ]
