# Generated by Django 5.2.8 on 2025-11-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_remove_livros_nome_emprestado_livros_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='data_cadastro',
            new_name='data_lancamento',
        ),
    ]
