# Generated by Django 5.2.8 on 2025-11-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_rename_data_cadastro_livros_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
