# Generated by Django 5.2.8 on 2025-11-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0020_alter_emprestimos_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='nome_esprestado',
            new_name='nome_emprestado',
        ),
        migrations.RenameField(
            model_name='emprestimos',
            old_name='nome_esprestado_anonimo',
            new_name='nome_emprestado_anonimo',
        ),
    ]
