# Generated by Django 5.2.8 on 2025-11-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0021_rename_nome_esprestado_emprestimos_nome_emprestado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='co_autor',
        ),
    ]
